name: Deploy Docker Image

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: artis3n/docker-ubuntu2010-ansible

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Build and Push - Latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ghcr.io/${{ IMAGE_NAME }}:latest
  
    - name: Deploy the Docker image to GitHub Container Registry (semver tag)
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: ${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        tag_semver: true

    - name: Deploy the Docker image to Docker Hub - Semver
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag_semver: true
